version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["ruby", "bin/main.rb"]
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - redis
    networks:
      - app_net
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
        - app_net
volumes:
    redis_data:
networks:
    app_net:
      driver: bridge
