version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["ruby", "bin/main.rb"]
    environment:
      - LOG_FILE=${LOG_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    depends_on:
      - redis
    networks:
      - app_net
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
        - app_net
volumes:
    redis_data:
networks:
    app_net:
      driver: bridge
